accounts/urls.py
from django.urls import path
from . import views
app_name = 'accounts'
urlpatterns = [ 
    path("register/",views.register, name="register" ),
    path("login/",views.login_user, name="login"),
    path("logout/",views.logout_user, name ="logout")
  
  
]

main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [ 
    path('', views.home, name="home"),
    path('detail/<int:id>/', views.detail, name="detail"),
    path('addmovies/', views.addmovie, name="addmovie"),
    path('editmovies/<int:id>/', views.edit_movie, name="edit_movie"),
    path('deletemovie/<int:id>/', views.delete_movie, name="delete_movie"),
]

moviereview/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

class Movie(models.Model):
    name =models.CharField(max_length=300)
    director =models.CharField(max_length=300)
    cast =models.CharField(max_length=300)
    description =models.TextField(max_length=5000)
    release_date =models.DateField()
    rating =models.FloatField(default=0.0)
    image = models.URLField(default=None,null=True)
    


    def __str__(self):
        return self.name
    # def __unicode__(self):
    #     return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta:
         model = User
         fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

main/forms.py
from django import forms
from .models import *


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'release_date', 'image')

accounts/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.contrib.auth import authenticate,login,logout

# Create your views here.
def register(request):
    if request.user.is_authenticated:
        return redirect("main:home")


    else:
        
        if request.method == 'POST':
            form = RegistrationForm(request.POST or None)

            if form.is_valid():
                user = form.save()

                # check the code below if it works without cleaned_data

                raw_password = form.cleaned_data.get('password1')

                user = authenticate(username=user.username, password=raw_password)

                login(request, user)


                return redirect("main:home")
        else:
            form = RegistrationForm()
            return render(request, "accounts/registration.html", {"form":form})



def login_user(request):
    if request.user.is_authenticated :
        
        return redirect("main:home")
    else:
            
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request,user)
                    print("yes")
                    return redirect("main:home")

                else:
                    return render(request, "accounts/login.html",{"error":"You'r request has timed out.Login again"})
            else:
                return render(request,"accounts/login.html",{"error":"Invalid username or password"})
        else:

            return render(request,"accounts/login.html")
            


def logout_user(request):
    if request.user.is_authenticated:

   
        logout(request)
    
        return redirect("main:home")
    else:
        return redirect("accounts:login")

    

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *


def home(request):
    
    allmovies = Movie.objects.all()

    context = {"movies":allmovies,}
    
    
    return render(request, 'main/index.html', context)

def detail(request,id):
    movie = Movie.objects.get(id=id)
    context = {
        "movie":movie,
    }
    return render(request, 'main/detail.html', context)


def addmovie(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST or None)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()

                    return redirect("main:home")
            else:
                form = MovieForm()
                return render(request,'main/addmovie.html',{"form":form,"controller":"Add Movie"})

        else:
            return redirect("main:home")

    else:
        return redirect("accounts:login")



def edit_movie(request,id):
    movie = Movie.objects.get(id = id)

    if request.user.is_authenticated:
        if request.user.is_superuser:
            if request.method == "POST":
                form = MovieForm(request.POST or None, instance = movie)

                if form.is_valid():
                    data = form.save(commit = False)
                    data.save()
                    return redirect("main:detail",id)


            else:
                form = MovieForm(request.POST or None, instance=movie)
                return render(request, 'main/addmovie.html', {"form":form,"controller":"Edit Movie"})

        else:
            return redirect("main:home")
    else:
        return redirect("accounts:login")

def delete_movie(request,id):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            movie = Movie.objects.get(  id = id )
            movie.delete()
            return redirect("main:home")
        else:
            return redirect("main:home")
    else:
        return redirect("main:login")

accounts/templates/accounts/login.html
{% extends 'main/base.html'%}
{% block content%}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">
                Login
            </h3>
            <form action="" method="POST">
                {%csrf_token%}
                <label for="username">Username</label>
                <input type="text" placeholder="Enter your username" class="form-control" name="username" >

                <label for="password">Password</label>
                <input type="password" placeholder="Enter your password" class="form-control" name="password">
                <br>

                <input type="submit" value="Login" class="btn btn-danger">

                {% if error%}
                <div class="text-center">
                    <i style="color: red;" >{{error}}</i> 

                </div>
               
                {% endif %}


            </form>
        </div>
    </div>
</div>

{%endblock%}

accounts/templates/accounts/registration.html
{% extends 'main/base.html'%}
{% load crispy_forms_tags %}

{% block content%}
<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">
                Register an Account
            </h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <input type="submit" value="Register" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>


{%endblock%}

main/templates/main/addmovie.html
{%extends 'main/base.html'%}

{% load crispy_forms_tags %}
{% block content%}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">
                {{ controller}}

            </h3>
            <form action="" method="POST">
                {% csrf_token %}

                {{form | crispy}}
                <input type="submit" value="{{ controller }}" class="btn btn-danger">



            </form>

        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Movie Review</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'main:home'%}">Movie Review</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse"  id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:home'%}">Home <span class="sr-only">(current)</span></a>
            </li>
            {%if user.is_authenticated %}
            {% if user.is_superuser%}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:addmovie'%}">Add Movie</a>
            </li>
            {% endif %}
            {% endif %}
            {% if user.is_authenticated%}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               {{user.username}} 
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">MyProfile</a>
                <a class="dropdown-item"href="{% url 'accounts:logout'%}">Logout</a>
              
              </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login'%}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register'%}">Register</a>
              </li>

            {%endif%}
            
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
  
    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/detail.html
{%extends 'main/base.html'%}

{% block content%}
<di class="container">
    <br>
    <div class="card">
        <div class="row">
            <div class="col-md-4">
              <img src="{{movie.image}}" alt="{{movie.name}}" class="img-fluid" width="70%" >
            </div>
            <div class="col-md-8">
                <h3>{{movie.name}}</h3>
                <p>{{movie.description}}</p>
                <h5>{{movie.release_date}}</h5>
                <h5>{{movie.rating}}</h5>

                {% if request.user.is_authentiated %}
                {% if request.user.is_superuser %}
                <a href="{% url 'main:edit_movie' movie.id %}" class="btn btn-warning">Edit movie</a>
                <a href="{% url 'main:delete_movie' movie.id %}" class="btn btn-danger">Delete movie</a>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
        
</di>
{%endblock%}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

    <div class="container">
        <br>

        <div class="card" id="backdrop">
            <div class="card-body">
                <div class="row">
                    {% for movie in movies%}
                    <div class="col-md-4">
                        <div class="card">
                            <div class="card-body">
                                <div class="text-center">
                                <img src="{{movie.image}}" alt="{{movie.name}}" class="img-fluid" width="75%"  >
                                <h3 class="text-center">{{movie.name}}</h3>
                                <i>{{movie.release_date}}</i>
                                <a href="{% url 'main:detail' movie.id %}">Read More</a>
                            </div>
                              
                                
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    {%endblock%}